SELECT NVL(SUM(A.DR),0) - NVL(SUM(A.CR),0) FROM MEMBERLEDGER A  WHERE A.MEMBERID = 'R-4455'  AND A.DOCDATE < '01-OCT-2020';
-- SELECT NVL(SUM(A.DR),0) - NVL(SUM(A.CR),0)    FROM MEMBERLEDGER A  WHERE A.MEMBERID = :b1  AND A.DOCDATE < :start_date

SELECT
	A.DOCDATE,
	A.DOCNO,
	A.AREA_DESC,
	A.MEMBERID,
	A.MEMBERNAME,
	A.DR,
	A.CR 
FROM
	MEMBERLEDGER A 
WHERE
	A.MEMBERID = 'R-4455'
	AND A.DOCDATE BETWEEN '01-OCT-2020'
	AND '31-OCT-2020'
ORDER BY
	DOCDATE;
	
-- SELECT A.DOCDATE, A.DOCNO , A.AREA_DESC , A.MEMBERID , A.MEMBERNAME , A.DR, A.CR
-- FROM MEMBERLEDGER A
-- WHERE A.MEMBERID = :MBR
-- AND A.DOCDATE BETWEEN :start_date AND :end_date
-- ORDER BY DOCDATE

-- SELECT A.DOCDATE, A.DOCNO , A.AREA_DESC , A.MEMBERID , A.MEMBERNAME , A.DR, A.CR
-- FROM MEMBERLEDGER A
-- WHERE A.MEMBERID = :MBR
-- AND A.DOCDATE BETWEEN :FDATE AND :TDATE
-- ORDER BY DOCDATE
